data:
  dataset: {name: hangouts-augmented3, samples: 4990, type: private}
  datasetLoadOption: batch
  kfold: 1
  mapping:
    categoria_conducta:
      options: {Normalization: false, Scaling: 1}
      port: Ignore
      shape: ''
      type: Numeric
    categoria_reaccion:
      options: {}
      port: OutputPort0
      shape: ''
      type: Categorical
    mensaje:
      options: {Normalization: false, Scaling: 1}
      port: InputPort0
      shape: ''
      type: Array
  numPorts: 1
  samples: {split: 4, test: 499, training: 3992, validation: 499}
  shuffle: true
model:
  connections:
  - {source: Input_1, target: Reshape_1}
  - {source: BatchNormalization_1, target: Activation_1}
  - {source: Activation_1, target: Convolution1D_7}
  - {source: BatchNormalization_14, target: Activation_7}
  - {source: Flatten_3, target: Dense_16}
  - {source: Dense_17, target: Dropout_13}
  - {source: Dense_73, target: Dropout_50}
  - {source: Dense_16, target: Dropout_12}
  - {source: Dropout_12, target: Dense_73}
  - {source: Dropout_50, target: Dense_17}
  - {source: Dropout_13, target: Dense_18}
  - {source: Convolution1D_7, target: BatchNormalization_14}
  - {source: Activation_7, target: MaxPooling1D_3}
  - {source: Reshape_1, target: Convolution1D_1}
  - {source: Dense_18, target: Output_3}
  - {source: MaxPooling1D_3, target: Flatten_3}
  - {source: Convolution1D_1, target: BatchNormalization_1}
  layers:
  - args: {}
    class: Input
    name: Input_1
    x: 35.360000000000014
    y: 47.94
  - args: {filter_length: '2', nb_filter: '16'}
    class: Convolution1D
    name: Convolution1D_1
    x: 31.990000000000002
    y: 293.21999999999997
  - args: {target_shape: '(300, 1)'}
    class: Reshape
    name: Reshape_1
    x: 34.60000000000001
    y: 165.51
  - args: {}
    class: BatchNormalization
    name: BatchNormalization_1
    x: 31.94000000000002
    y: 395.6
  - args: {activation: relu}
    class: Activation
    name: Activation_1
    x: 30.61
    y: 504.65999999999997
  - args: {filter_length: '2', nb_filter: '8'}
    class: Convolution1D
    name: Convolution1D_7
    x: 341
    y: 303
  - args: {}
    class: BatchNormalization
    name: BatchNormalization_14
    x: 345
    y: 390
  - args: {activation: relu}
    class: Activation
    name: Activation_7
    x: 350.61
    y: 484.65999999999997
  - args: {}
    class: MaxPooling1D
    name: MaxPooling1D_3
    x: 336
    y: 625
  - args: {}
    class: Flatten
    name: Flatten_3
    x: 713
    y: 159
  - args: {activation: relu, output_dim: '500'}
    class: Dense
    name: Dense_16
    x: 711
    y: 305
  - args: {p: '0.5'}
    class: Dropout
    name: Dropout_12
    x: 710
    y: 395
  - args: {activation: relu, output_dim: '100'}
    class: Dense
    name: Dense_17
    x: 699
    y: 666
  - args: {p: '0.5'}
    class: Dropout
    name: Dropout_13
    x: 699
    y: 760
  - args: {activation: softmax, output_dim: '4'}
    class: Dense
    name: Dense_18
    x: 702
    y: 877
  - args: {}
    class: Output
    name: Output_3
    x: 699
    y: 959
  - args: {activation: relu, output_dim: '300'}
    class: Dense
    name: Dense_73
    x: 670
    y: 494
  - args: {p: '0.5'}
    class: Dropout
    name: Dropout_50
    x: 679
    y: 586
params:
  advance_params: true
  batch_size: 32
  is_custom_loss: false
  loss_func: categorical_crossentropy
  num_epoch: 100
  optimizer: {name: Adadelta}
project: prueba-cnn-hangouts-augmented
